id: PDFBF2AF7
initial_creation_type: input
source_metadata:
  title: Yamāntaka Series
  language: es
  description: 'Texts related to Yamāntaka (gshin rje gshed), the wrathful form of
    Mañjuśrī:'
  volume:
    eab5274fde034d418f7321d138723402:
      title: Daily Practice of Mañjuśrī Yamāntaka
      parent: Sādhanas
    1a59cc67ac0e4e80951b218ec0fd2d06:
      title: The Method to Pacify All Epidemics, Illnesses and Pandemics from the
        Sixty Solitary Forms of Yamāntaka
      parent: Sādhanas
created_at: '2022-03-01T06:35:53.230016'
last_modified_at: '2022-03-01T06:35:53.230018'
